apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: payment-order-ouroinvest-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: payment-order-ouroinvest-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /webhook/ouroinvest/payment_order
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /webhook/ouroinvest/payment_order
